### ISSUE TITLE
Telemetry Idea

### ISSUE THREAD

**Issue by ccunni3** [Froz3nArcher/SmartBlinds#1]
Let me first start by saying that this isn't an issue at all but a suggestion to fulfill your desire for a telemetry solution. What if you used some type of packet radio to send out logging data and could possibly receive commands. I know Adafruit sells a wide assay of packet radios. They are low power and can actually blast information quite a range. You could then use a raspberryPi or another radio as the "base station" to be the interface between the local computer network and the micro controller sensor network. Let me know what you think. Also, let me say that I think this is a great project!

**Comment by Froz3nArcher** [comment]
Thanks for the kind words!  I just took a look at the Feathers...  They've got a pretty sizable current draw when transmitting, which would really chew into the battery.  I think my setup is about 1.5 mA when idle, and 27 mA when running.  A Feather would add an additional 50 mA when running - unknown when idle or "disabled."  That has been the biggest issue for me in looking at some kind of wireless telemetry/commanding capability.  
And it'd probably have to be awake longer to listen for possible commands - further increasing the battery drain.  One of these days I'll try something like that just to see if it's plausible, or if it shortens the lifespan.  It's possible that by charging via sun every day it wouldn't matter.  The real test would be a long cloudy spell during the summer - when I get the least amount of charging time.
But thanks for the Feather suggestion, I'll have to try it - I had only looked at Wifi and Bluetooth before.  My wife was tired of having the ladder in the entranceway so the blinds had to go up without it.  :)
